function main(args) {
    return { error: "This error thrown on purpose by the action."};
}
